add_lunch_combo pa_i9100-userdebug
add_lunch_combo pa_i9300-userdebug
add_lunch_combo pa_maguro-userdebug
add_lunch_combo pa_toro-userdebug
add_lunch_combo pa_toroplus-userdebug
add_lunch_combo pa_grouper-userdebug

