add_lunch_combo pa_grouper-userdebug
add_lunch_combo pa_maguro-userdebug
add_lunch_combo pa_mako-userdebug
add_lunch_combo pa_manta-userdebug
add_lunch_combo pa_toro-userdebug
add_lunch_combo pa_toroplus-userdebug
